# Generated by Django 2.2 on 2020-02-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0035_auto_20200221_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_1',
            name='FeedRate_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_2',
            name='FeedRate_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_3',
            name='FeedRate_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_4',
            name='FeedRate_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_5',
            name='FeedRate_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_6',
            name='FeedRate_value',
            field=models.IntegerField(null=True),
        ),
    ]
