# Generated by Django 2.2 on 2020-02-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0037_auto_20200221_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_1',
            name='ScanningRate_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_1',
            name='laser_power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_2',
            name='ScanningRate_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_2',
            name='laser_power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_3',
            name='ScanningRate_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_3',
            name='laser_power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_4',
            name='ScanningRate_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_4',
            name='laser_power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_5',
            name='ScanningRate_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_5',
            name='laser_power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_6',
            name='ScanningRate_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_6',
            name='laser_power',
            field=models.IntegerField(null=True),
        ),
    ]
