# Generated by Django 2.2 on 2019-11-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_code', models.CharField(max_length=3)),
                ('element_name', models.CharField(max_length=4)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CNCProcessAutoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=20, null=True)),
                ('X_value', models.FloatField(null=True)),
                ('Y_value', models.FloatField(null=True)),
                ('Z_value', models.FloatField(null=True)),
                ('ScanningRate_value', models.FloatField(null=True)),
                ('SReal_value', models.FloatField(null=True)),
                ('FeedRate_value', models.IntegerField(null=True)),
                ('GState_value', models.CharField(max_length=50, null=True)),
                ('MState_value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CNCStatusCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('model_number', models.CharField(max_length=30, null=True)),
                ('device_Number', models.CharField(max_length=30, null=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeatTreatmentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heattreatmentstate_name', models.CharField(max_length=30, unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LAM_TechInst_Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('serial_note', models.CharField(blank=True, max_length=50)),
                ('serial_content', models.CharField(blank=True, max_length=200)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LAMMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=20)),
                ('material_name', models.CharField(max_length=50)),
                ('nominal_composition', models.CharField(max_length=50, null=True)),
                ('available', models.BooleanField(default=True)),
                ('chemicalelements', models.ManyToManyField(to='LAMProcessData.ChemicalElement')),
            ],
        ),
        migrations.CreateModel(
            name='LAMProcessMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangement_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LAMProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, null=True, unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LAMProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_code', models.CharField(max_length=30, null=True, unique=True)),
                ('product_name', models.CharField(max_length=30, null=True, unique=True)),
                ('product_symbol', models.CharField(max_length=10, null=True, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='LAMProductionWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktype_name', models.CharField(max_length=50, unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicalTest_Tensile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(blank=True, max_length=10, null=True)),
                ('test_temperature', models.FloatField(blank=True, default=25, null=True)),
                ('tensile_strength', models.FloatField(blank=True, null=True)),
                ('yield_strength', models.FloatField(blank=True, null=True)),
                ('elongation', models.FloatField(blank=True, null=True)),
                ('areareduction', models.FloatField(blank=True, null=True)),
                ('modulus', models.FloatField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicalTest_Toughness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(blank=True, max_length=10, null=True)),
                ('test_temperature', models.FloatField(blank=True, default=25, null=True)),
                ('toughness', models.FloatField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=30)),
                ('rawstock_supplier', models.CharField(blank=True, max_length=30, null=True)),
                ('available', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='RawStockCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=10, unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamplingDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DirectionName', models.CharField(max_length=30, null=True)),
                ('DirectionCode', models.CharField(max_length=5)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamplingPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionName', models.CharField(max_length=30, null=True)),
                ('PositionCode', models.CharField(max_length=5)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryParameter_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worksection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('cnc_computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnc_computer', to='LAMProcessData.Computer')),
                ('desktop_computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desktop_computer', to='LAMProcessData.Computer')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='RawStockSendRetrieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateField(null=True)),
                ('raw_stock_sent_amount', models.FloatField(blank=True, null=True)),
                ('retrieve_time', models.DateField(blank=True, null=True)),
                ('raw_stock_unused_amount', models.FloatField(blank=True, null=True)),
                ('raw_stock_primaryretrieve_amount', models.FloatField(blank=True, null=True)),
                ('raw_stock_secondaryretrieve_amount', models.FloatField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('LAM_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMProcessMission')),
                ('raw_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.RawStock')),
            ],
        ),
        migrations.AddField(
            model_name='rawstock',
            name='rawstock_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.RawStockCategory'),
        ),
        migrations.CreateModel(
            name='Process_Oxygendata_Date_Worksection_indexing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_date', models.DateField()),
                ('index_date_int', models.IntegerField(null=True)),
                ('oxygendata_start_id', models.PositiveIntegerField(null=True)),
                ('oxygendata_finish_id', models.PositiveIntegerField(null=True)),
                ('work_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.Worksection')),
            ],
        ),
        migrations.CreateModel(
            name='Process_Mission_timecut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_finish_time', models.DateTimeField(blank=True, null=True)),
                ('laserdata_start_id', models.PositiveIntegerField(null=True)),
                ('laserdata_finish_id', models.PositiveIntegerField(null=True)),
                ('oxygendata_start_id', models.PositiveIntegerField(null=True)),
                ('oxygendata_finish_id', models.PositiveIntegerField(null=True)),
                ('cncstatusdata_start_id', models.PositiveIntegerField(null=True)),
                ('cncstatusdata_finish_id', models.PositiveIntegerField(null=True)),
                ('process_mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission')),
            ],
        ),
        migrations.CreateModel(
            name='Process_Laserdata_Date_Worksection_indexing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_date', models.DateField()),
                ('index_date_int', models.IntegerField(null=True)),
                ('laserdata_start_id', models.PositiveIntegerField(null=True)),
                ('laserdata_finish_id', models.PositiveIntegerField(null=True)),
                ('work_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.Worksection')),
            ],
        ),
        migrations.CreateModel(
            name='Process_CNCStatusdata_Date_Worksection_indexing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_date', models.DateField()),
                ('index_date_int', models.IntegerField(null=True)),
                ('cncstatusdata_start_id', models.PositiveIntegerField(null=True)),
                ('cncstatusdata_finish_id', models.PositiveIntegerField(null=True)),
                ('work_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.Worksection')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicochemicalTest_Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_date', models.DateField(null=True)),
                ('available', models.BooleanField(default=True)),
                ('LAM_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMProduct')),
                ('LAM_techinst_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAM_TechInst_Serial')),
                ('RawStock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.RawStock')),
                ('chemicaltest', models.ManyToManyField(blank=True, to='LAMProcessData.ChemicalTest')),
                ('heat_treatment_state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.HeatTreatmentState')),
                ('mechanicaltest_tensile', models.ManyToManyField(blank=True, to='LAMProcessData.MechanicalTest_Tensile')),
                ('mechanicaltest_toughness', models.ManyToManyField(blank=True, to='LAMProcessData.MechanicalTest_Toughness')),
            ],
        ),
        migrations.CreateModel(
            name='Oxygendata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_time', models.DateTimeField(auto_now=True)),
                ('oxygen_value', models.IntegerField()),
                ('oxygen_sensor_value', models.FloatField()),
                ('internal_pressure_value', models.FloatField()),
                ('process_mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission')),
                ('work_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.Worksection')),
            ],
        ),
        migrations.AddField(
            model_name='mechanicaltest_toughness',
            name='sampling_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.SamplingDirection'),
        ),
        migrations.AddField(
            model_name='mechanicaltest_toughness',
            name='sampling_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.SamplingPosition'),
        ),
        migrations.AddField(
            model_name='mechanicaltest_tensile',
            name='sampling_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.SamplingDirection'),
        ),
        migrations.AddField(
            model_name='mechanicaltest_tensile',
            name='sampling_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.SamplingPosition'),
        ),
        migrations.CreateModel(
            name='Laserdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_time', models.DateTimeField()),
                ('laser_power', models.IntegerField()),
                ('laser_lightpath_temperature', models.FloatField()),
                ('laser_laser_temperature', models.FloatField()),
                ('process_mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission')),
                ('work_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.Worksection')),
            ],
        ),
        migrations.CreateModel(
            name='LAMTechniqueInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_code', models.CharField(max_length=20)),
                ('instruction_name', models.CharField(max_length=50)),
                ('version_code', models.CharField(max_length=3)),
                ('version_number', models.PositiveIntegerField()),
                ('temporary', models.BooleanField(default=False)),
                ('filed', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(blank=True, to='LAMProcessData.LAMProduct')),
                ('product_category', models.ManyToManyField(blank=True, to='LAMProcessData.LAMProductCategory')),
            ],
        ),
        migrations.AddField(
            model_name='lamproduct',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMProductCategory'),
        ),
        migrations.AddField(
            model_name='lamprocessmission',
            name='LAM_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMProduct'),
        ),
        migrations.AddField(
            model_name='lamprocessmission',
            name='LAM_techinst_serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAM_TechInst_Serial'),
        ),
        migrations.AddField(
            model_name='lamprocessmission',
            name='work_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.Worksection'),
        ),
        migrations.AddField(
            model_name='lam_techinst_serial',
            name='serial_worktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMProductionWorkType'),
        ),
        migrations.AddField(
            model_name='lam_techinst_serial',
            name='technique_instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMTechniqueInstruction'),
        ),
        migrations.CreateModel(
            name='CNCProcessStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_time', models.DateTimeField(null=True)),
                # ('acquisition_timestamp', models.DecimalField(decimal_places=1, max_digits=10)),
                ('screen_image', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d')),
                ('if_checked', models.BooleanField(default=False)),
                ('check_datetime', models.DateTimeField(blank=True, null=True)),
                ('if_auto_exec_intr', models.BooleanField(blank=True, null=True)),
                ('if_exec_intr', models.BooleanField(blank=True, null=True)),
                ('if_interrupt_intr', models.BooleanField(blank=True, null=True)),
                ('program_name', models.CharField(max_length=20, null=True)),
                ('Z_value', models.FloatField(null=True)),
                ('autodata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.CNCProcessAutoData')),
                ('process_mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission')),
                ('status_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.CNCStatusCategory')),
                ('work_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.Worksection')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalTest_Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.ChemicalElement')),
            ],
        ),
        migrations.AddField(
            model_name='chemicaltest',
            name='elements',
            field=models.ManyToManyField(to='LAMProcessData.ChemicalTest_Element'),
        ),
        migrations.AddField(
            model_name='chemicaltest',
            name='sampling_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LAMProcessData.SamplingPosition'),
        ),
    ]
