# Generated by Django 2.2 on 2019-11-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cncprocessstatus',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='laserdata',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='oxygendata',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
    ]
