# Generated by Django 2.2 on 2019-12-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0003_auto_20191130_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process_cncstatusdata_date_worksection_indexing',
            old_name='cncstatusdata_finish_id',
            new_name='data_finish_id',
        ),
        migrations.RenameField(
            model_name='process_cncstatusdata_date_worksection_indexing',
            old_name='cncstatusdata_start_id',
            new_name='data_start_id',
        ),
        migrations.RenameField(
            model_name='process_laserdata_date_worksection_indexing',
            old_name='laserdata_finish_id',
            new_name='data_finish_id',
        ),
        migrations.RenameField(
            model_name='process_laserdata_date_worksection_indexing',
            old_name='laserdata_start_id',
            new_name='data_start_id',
        ),
        migrations.RenameField(
            model_name='process_oxygendata_date_worksection_indexing',
            old_name='oxygendata_finish_id',
            new_name='data_finish_id',
        ),
        migrations.RenameField(
            model_name='process_oxygendata_date_worksection_indexing',
            old_name='oxygendata_start_id',
            new_name='data_start_id',
        ),
    ]
