# Generated by Django 2.2 on 2019-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0004_auto_20191207_0015'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cncprocessstatus',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='laserdata',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='oxygendata',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        migrations.AddField(
            model_name='process_oxygendata_date_worksection_indexing',
            name='data_string',
            field=models.TextField(null=True),
        ),
    ]
