# Generated by Django 2.2 on 2019-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0005_auto_20191208_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_cncstatusdata_date_worksection_indexing',
            name='data_string',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='process_laserdata_date_worksection_indexing',
            name='data_string',
            field=models.TextField(null=True),
        ),
    ]
