# Generated by Django 2.2 on 2019-12-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0006_auto_20191208_1032'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cncprocessstatus',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='laserdata',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='oxygendata',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        migrations.AlterField(
            model_name='process_mission_timecut',
            name='cncstatusdata_finish_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process_mission_timecut',
            name='cncstatusdata_start_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process_mission_timecut',
            name='laserdata_finish_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process_mission_timecut',
            name='laserdata_start_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process_mission_timecut',
            name='oxygendata_finish_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process_mission_timecut',
            name='oxygendata_start_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
