# Generated by Django 2.2 on 2019-12-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0009_auto_20191209_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cncprocessstatus',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laserdata',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oxygendata',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_mission_timecut',
            name='process_mission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission'),
        ),
    ]
