# Generated by Django 2.2 on 2019-12-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0010_auto_20191209_0724'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cncprocessstatus',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='laserdata',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='oxygendata',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        migrations.AlterIndexTogether(
            name='cncprocessstatus',
            index_together={('work_section', 'process_mission', 'acquisition_timestamp')},
        ),
        migrations.AlterIndexTogether(
            name='laserdata',
            index_together={('work_section', 'process_mission', 'acquisition_timestamp')},
        ),
        migrations.AlterIndexTogether(
            name='oxygendata',
            index_together={('work_section', 'process_mission', 'acquisition_timestamp')},
        ),
    ]
