# Generated by Django 2.2 on 2019-12-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0011_auto_20191211_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process_mission_timecut',
            old_name='cncstatusdata_finish_id',
            new_name='cncstatusdata_finish_recordid',
        ),
        migrations.RenameField(
            model_name='process_mission_timecut',
            old_name='cncstatusdata_start_id',
            new_name='cncstatusdata_start_recordid',
        ),
        migrations.RenameField(
            model_name='process_mission_timecut',
            old_name='laserdata_finish_id',
            new_name='laserdata_finish_recordid',
        ),
        migrations.RenameField(
            model_name='process_mission_timecut',
            old_name='laserdata_start_id',
            new_name='laserdata_start_recordid',
        ),
        migrations.RenameField(
            model_name='process_mission_timecut',
            old_name='oxygendata_finish_id',
            new_name='oxygendata_finish_recordid',
        ),
        migrations.RenameField(
            model_name='process_mission_timecut',
            old_name='oxygendata_start_id',
            new_name='oxygendata_start_recordid',
        ),
    ]
