# Generated by Django 2.2 on 2019-12-29 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0012_auto_20191211_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksection_Current_LAMProcessMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission')),
                ('work_section', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.Worksection')),
            ],
        ),
    ]
