# Generated by Django 2.2 on 2019-12-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0014_worksection_current_lamprocessmission_if_onwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksection_current_lamprocessmission',
            name='if_onwork',
            field=models.BooleanField(default=False),
        ),
    ]
