# Generated by Django 2.2 on 2020-01-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0015_auto_20191229_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMProcessParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('precondition', models.TextField(null=True)),
                ('expression', models.TextField(null=True)),
            ],
        ),
    ]
