# Generated by Django 2.2 on 2020-02-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0016_lamprocessparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMProcessParameterConditionalCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('precondition', models.TextField(null=True)),
                ('expression', models.TextField(null=True)),
                ('comment', models.CharField(max_length=80, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lamprocessparameters',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='lamprocessparameters',
            name='level',
        ),
        migrations.RemoveField(
            model_name='lamprocessparameters',
            name='precondition',
        ),
        migrations.AddField(
            model_name='lam_techinst_serial',
            name='process_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMProcessParameters'),
        ),
        migrations.AddField(
            model_name='lamprocessparameters',
            name='comment',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lamprocessparameters',
            name='name',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lamprocessparameters',
            name='conditional_cell',
            field=models.ManyToManyField(blank=True, to='LAMProcessData.LAMProcessParameterConditionalCell'),
        ),
    ]
