# Generated by Django 2.2 on 2020-02-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0018_lamprocessparameters_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamprocessparameterconditionalcell',
            name='comment',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
