# Generated by Django 2.2 on 2020-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0020_auto_20200210_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamprocessparameterconditionalcell',
            name='comment',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
