# Generated by Django 2.2 on 2020-02-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0022_process_realtime_finedata_by_worksectionid_1_process_realtime_finedata_by_worksectionid_2_process_re'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_1',
            name='program_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_2',
            name='program_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_3',
            name='program_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_4',
            name='program_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_5',
            name='program_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_6',
            name='program_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
