# Generated by Django 2.2 on 2020-02-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0023_auto_20200212_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_1',
            name='process_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission'),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_2',
            name='process_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission'),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_3',
            name='process_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission'),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_4',
            name='process_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission'),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_5',
            name='process_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission'),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_6',
            name='process_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission'),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_1',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_2',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_3',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_4',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_5',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_6',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(),
        ),
    ]
