# Generated by Django 2.2 on 2020-02-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0025_auto_20200212_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_1',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_2',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_3',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_4',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_5',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_6',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
