# Generated by Django 2.2 on 2020-02-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0026_auto_20200213_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_1',
            name='oxygen_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_2',
            name='oxygen_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_3',
            name='oxygen_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_4',
            name='oxygen_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_5',
            name='oxygen_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process_realtime_finedata_by_worksectionid_6',
            name='oxygen_value',
            field=models.FloatField(null=True),
        ),
    ]
