# Generated by Django 2.2 on 2020-02-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0027_auto_20200213_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_1',
            name='acquisition_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_2',
            name='acquisition_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_3',
            name='acquisition_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_4',
            name='acquisition_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_5',
            name='acquisition_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process_realtime_finedata_by_worksectionid_6',
            name='acquisition_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
