# Generated by Django 2.2 on 2020-02-16 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LAMProcessData', '0028_auto_20200215_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process_Inspect_FineData_DiscordantRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.PositiveIntegerField(unique=True)),
                ('finish_timestamp', models.PositiveIntegerField(unique=True)),
                ('parameter_realvalue', models.CharField(max_length=50, null=True)),
                ('parameter_conditionalcell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessParameterConditionalCell')),
                ('process_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission')),
            ],
        ),
        migrations.CreateModel(
            name='LAMProcess_Worksection_Operate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_timestamp', models.PositiveIntegerField(unique=True)),
                ('operate_information', models.CharField(max_length=50, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('process_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission')),
            ],
        ),
    ]
