# Generated by Django 2.2 on 2020-02-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0029_lamprocess_worksection_operate_process_inspect_finedata_discordantrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamprocessparameterconditionalcell',
            name='instead_Cond_Cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMProcessParameterConditionalCell', verbose_name='替代条件单元'),
        ),
    ]
