# Generated by Django 2.2 on 2020-02-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0030_lamprocessparameterconditionalcell_instead_cond_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamprocessparameters',
            name='conditional_cell',
            field=models.ManyToManyField(blank=True, related_name='CondCell_Parameter', to='LAMProcessData.LAMProcessParameterConditionalCell'),
        ),
    ]
