# Generated by Django 2.2 on 2020-02-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0033_auto_20200219_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_inspect_finedata_discordantrecords',
            name='finish_timestamp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='process_inspect_finedata_discordantrecords',
            name='start_timestamp',
            field=models.PositiveIntegerField(),
        ),
    ]
