# Generated by Django 2.2 on 2020-02-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0034_auto_20200219_2241'),
    ]

    operations = [

        migrations.AlterIndexTogether(
            name='process_realtime_finedata_by_worksectionid_1',
            index_together={('process_mission', 'acquisition_timestamp', 'Z_value', 'laser_power', 'ScanningRate_value')},
        ),
        migrations.AlterIndexTogether(
            name='process_realtime_finedata_by_worksectionid_2',
            index_together={('process_mission', 'acquisition_timestamp', 'Z_value', 'laser_power', 'ScanningRate_value')},
        ),
        migrations.AlterIndexTogether(
            name='process_realtime_finedata_by_worksectionid_3',
            index_together={('process_mission', 'acquisition_timestamp', 'Z_value', 'laser_power', 'ScanningRate_value')},
        ),
        migrations.AlterIndexTogether(
            name='process_realtime_finedata_by_worksectionid_4',
            index_together={('process_mission', 'acquisition_timestamp', 'Z_value', 'laser_power', 'ScanningRate_value')},
        ),
        migrations.AlterIndexTogether(
            name='process_realtime_finedata_by_worksectionid_5',
            index_together={('process_mission', 'acquisition_timestamp', 'Z_value', 'laser_power', 'ScanningRate_value')},
        ),
        migrations.AlterIndexTogether(
            name='process_realtime_finedata_by_worksectionid_6',
            index_together={('process_mission', 'acquisition_timestamp', 'Z_value', 'laser_power', 'ScanningRate_value')},
        ),
    ]
