# Generated by Django 2.2 on 2020-02-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0036_auto_20200222_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lamprocessparameteraccumulatecell',
            name='K',
        ),
        migrations.RemoveField(
            model_name='lamprocessparameteraccumulatecell',
            name='M3',
        ),
        migrations.AddField(
            model_name='lamprocessparameteraccumulatecell',
            name='l',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lamprocessparameteraccumulatecell',
            name='tm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Process_Accumulatedata_Date_Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_date', models.DateField()),
                ('index_date_int', models.IntegerField(null=True)),
                ('minute_index', models.IntegerField(null=True)),
                ('P', models.TextField(null=True)),
                ('K', models.TextField(null=True)),
                ('Z_value', models.TextField(null=True)),
                ('process_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission')),
            ],
        ),
    ]
