# Generated by Django 2.2 on 2020-02-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0038_auto_20200223_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_accumulatedata_date_mission',
            name='Z_value',
        ),
        migrations.CreateModel(
            name='Process_CNCData_Date_Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_date', models.DateField()),
                ('index_date_int', models.IntegerField(null=True)),
                ('minute_index', models.IntegerField(null=True)),
                ('Z_value', models.TextField(null=True)),
                ('layer_thickness', models.TextField(null=True)),
                ('process_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMProcessData.LAMProcessMission')),
            ],
        ),
    ]
