# Generated by Django 2.2 on 2020-02-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0040_auto_20200226_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process_Accumulatedata_Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(null=True, upload_to='./media/analyse/ACCUMULATEDATA/')),
                ('M1', models.FloatField(blank=True, null=True)),
                ('M2', models.FloatField(blank=True, null=True)),
                ('l', models.FloatField(blank=True, null=True)),
                ('tm', models.FloatField(blank=True, null=True)),
                ('process_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mission_Accumulatedata', to='LAMProcessData.LAMProcessMission')),
            ],
        ),
        migrations.CreateModel(
            name='Process_CNCData_Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(null=True, upload_to='./media/analyse/CNCData/')),
                ('process_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mission_CNCData', to='LAMProcessData.LAMProcessMission')),
            ],
        ),
        migrations.RemoveField(
            model_name='process_cncdata_date_mission',
            name='process_mission',
        ),
        migrations.DeleteModel(
            name='Process_Accumulatedata_Date_Mission',
        ),
        migrations.DeleteModel(
            name='Process_CNCData_Date_Mission',
        ),
    ]
