# Generated by Django 2.2 on 2020-02-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0041_auto_20200226_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_accumulatedata_mission',
            name='data_file',
            field=models.FileField(null=True, upload_to='./analyse/ACCUMULATEDATA/'),
        ),
        migrations.AlterField(
            model_name='process_cncdata_mission',
            name='data_file',
            field=models.FileField(null=True, upload_to='./analyse/CNCData/'),
        ),
        migrations.AlterField(
            model_name='process_mission_timecut',
            name='process_mission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mission_Timecut', to='LAMProcessData.LAMProcessMission'),
        ),
        migrations.CreateModel(
            name='Process_CNCData_Layer_Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(null=True, upload_to='./analyse/CNCData/')),
                ('process_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mission_LayerCNCData', to='LAMProcessData.LAMProcessMission')),
            ],
        ),
    ]
