# Generated by Django 2.2 on 2020-02-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0042_auto_20200227_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_cncdata_mission',
            name='accumulate_data_file',
            field=models.FileField(null=True, upload_to='./analyse/CNCData/'),
        ),
    ]
