# Generated by Django 2.2 on 2020-02-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0043_process_cncdata_mission_accumulate_data_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process_cncdata_mission',
            old_name='data_file',
            new_name='zvalue_data_file',
        ),
    ]
