# Generated by Django 2.2 on 2020-03-12 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0045_auto_20200312_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'permissions': (('SystemInformation', '基础信息'), ('Technique', '技术管理'), ('Quality', '质量管理'), ('Manufacture', '生产管理'), ('Operator_LAM', '激光成形操作者'), ('Operator_HT', '热处理操作者'), ('Operator_STOREROOM', '库房管理者'), ('Operator_INSP', '检验者'))},
        ),
    ]
