# Generated by Django 2.2 on 2020-03-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0046_auto_20200312_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicalTest_FractureToughness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(blank=True, max_length=10, null=True)),
                ('test_temperature', models.FloatField(blank=True, default=25, null=True)),
                ('fracturetoughness_KIC', models.FloatField(blank=True, null=True)),
                ('fracturetoughness_KQ', models.FloatField(blank=True, null=True)),
                ('Effectiveness', models.BooleanField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('sampling_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.SamplingDirection')),
                ('sampling_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.SamplingPosition')),
            ],
        ),
        migrations.AddField(
            model_name='physicochemicaltest_mission',
            name='mechanicaltest_fracturetoughness',
            field=models.ManyToManyField(blank=True, to='LAMProcessData.MechanicalTest_FractureToughness'),
        ),
    ]
