# Generated by Django 2.2 on 2020-03-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0047_auto_20200313_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamproductionworktype',
            name='selectable_HeatTreatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lamproductionworktype',
            name='selectable_LAM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lamproductionworktype',
            name='selectable_PhyChemTest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lamproductionworktype',
            name='selectable_RawStockSendRetrieve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lamproductionworktype',
            name='selectable_Scheduling',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lamproductionworktype',
            name='selectable_Weighing',
            field=models.BooleanField(default=False),
        ),
    ]
