# Generated by Django 2.2 on 2020-03-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0049_auto_20200314_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFImageCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('imagecode', models.TextField(null=True)),
                ('text', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_worktype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkType_ImageCode', to='LAMProcessData.LAMProductionWorkType')),
            ],
        ),
    ]
