# Generated by Django 2.2 on 2020-03-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0050_pdfimagecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfimagecode',
            name='imagecode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfimagecode',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterIndexTogether(
            name='pdfimagecode',
            index_together={('image_width', 'image_height',  'text')},
        ),
        migrations.RemoveField(
            model_name='pdfimagecode',
            name='serial_worktype',
        ),
    ]
