# Generated by Django 2.2 on 2020-03-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0054_auto_20200326_2148'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='pdfimagecode',
            index_together=set(),
        ),
    ]
