# Generated by Django 2.2 on 2020-03-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0056_auto_20200326_2152'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='pdfimagecode',
            index_together=set(),
        ),
    ]
