# Generated by Django 2.2 on 2020-03-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0057_auto_20200326_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfimagecode',
            name='imagecode',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
