# Generated by Django 2.2 on 2020-03-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0058_auto_20200326_2155'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='pdfimagecode',
            index_together={('image_width', 'image_height', 'text')},
        ),
    ]
