# Generated by Django 2.2 on 2020-03-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0059_auto_20200326_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfimagecode',
            name='OriginalImage',
            field=models.ImageField(blank=True, null=True, upload_to='PDFCode/'),
        ),
        migrations.AlterField(
            model_name='pdfimagecode',
            name='imagecode',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lam_techinst_serial',
            unique_together={('technique_instruction', 'serial_number')},
        ),
    ]
