# Generated by Django 2.2 on 2020-04-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0063_auto_20200404_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawstock',
            name='use_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawstocksendretrieve',
            name='raw_stock_primaryretrieve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='RawStock_RetrieveAsPrimaryFrom', to='LAMProcessData.RawStock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawstocksendretrieve',
            name='raw_stock_secondaryretrieve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='RawStock_RetrieveAssecondaryFrom', to='LAMProcessData.RawStock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lamprocessmission',
            name='LAM_product',
            field=models.ManyToManyField(related_name='Product_LAMProcessMission', to='LAMProcessData.LAMProduct'),
        ),
        migrations.AlterField(
            model_name='rawstockcategory',
            name='Category_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='RawStock_Powder_GroupPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('raw_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RawStock_GroupPart', to='LAMProcessData.RawStock')),
            ],
        ),
        migrations.CreateModel(
            name='RawStock_Powder_GroupBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouped_time', models.DateField()),
                ('New_RawStock_GroupPart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RawStockGroupPart_AsNewBatch', to='LAMProcessData.RawStock_Powder_GroupPart')),
                ('parents_RawStock_GroupPart', models.ManyToManyField(related_name='RawStockGroupPart_AsParentsBatch', to='LAMProcessData.RawStock_Powder_GroupPart')),
            ],
        ),
    ]
