# Generated by Django 2.2 on 2020-04-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0065_auto_20200417_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawstock_powder_grouppart',
            name='raw_stock',
        ),
        migrations.RemoveField(
            model_name='rawstocksendretrieve',
            name='raw_stock_primaryretrieve',
        ),
        migrations.RemoveField(
            model_name='rawstocksendretrieve',
            name='raw_stock_secondaryretrieve',
        ),
        migrations.DeleteModel(
            name='RawStock_Powder_GroupBatch',
        ),
        migrations.DeleteModel(
            name='RawStock_Powder_GroupPart',
        ),
    ]
