# Generated by Django 2.2 on 2020-04-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0066_auto_20200417_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawStockSendAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateField(null=True)),
                ('raw_stock_sent_amount', models.FloatField(blank=True, null=True)),
                ('raw_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.RawStock')),
            ],
        ),
        migrations.AddField(
            model_name='rawstocksendretrieve',
            name='send_addition',
            field=models.ManyToManyField(related_name='RawStockSendAddition_Send', to='LAMProcessData.RawStockSendAddition'),
        ),
    ]
