# Generated by Django 2.2 on 2020-04-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0067_auto_20200417_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawstock',
            name='use_up',
        ),
    ]
