# Generated by Django 2.2 on 2020-04-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0068_remove_rawstock_use_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawstocksendretrieve',
            name='send_addition',
            field=models.ManyToManyField(blank=True, null=True, related_name='RawStockSendAddition_Send', to='LAMProcessData.RawStockSendAddition'),
        ),
    ]
