# Generated by Django 2.2 on 2020-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0070_defectpicture_lamproductsubarea_machiningstate_mtdefectinformation_nondestructivetest_mission_ptdefe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicochemicaltest_mission',
            name='LAM_product',
        ),
        migrations.AddField(
            model_name='physicochemicaltest_mission',
            name='LAM_product',
            field=models.ManyToManyField(blank=True, null=True, to='LAMProcessData.LAMProduct'),
        ),
    ]
