# Generated by Django 2.2 on 2020-05-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0071_auto_20200501_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nondestructivetest_mission',
            old_name='heattreatmentstate',
            new_name='heat_treatment_state',
        ),
        migrations.RenameField(
            model_name='nondestructivetest_mission',
            old_name='machiningstate',
            new_name='machining_state',
        ),
        migrations.AddField(
            model_name='nondestructivetest_mission',
            name='RawStock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.RawStock'),
        ),
    ]
