# Generated by Django 2.2 on 2020-05-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0072_auto_20200502_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtdefectinformation',
            name='DefectCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='ptdefectinformation',
            name='DefectCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='rtdefectinformation',
            name='DefectCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='utdefectinformation',
            name='DefectCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='LAM_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMProduct', verbose_name='产品编号'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='LAM_techinst_serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAM_TechInst_Serial', verbose_name='检测工序'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='MT_defect',
            field=models.ManyToManyField(related_name='MTDefect_NDTMission', to='LAMProcessData.MTDefectInformation', verbose_name='磁粉缺陷'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='PT_defect',
            field=models.ManyToManyField(related_name='PTDefect_NDTMission', to='LAMProcessData.PTDefectInformation', verbose_name='荧光缺陷'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='RT_defect',
            field=models.ManyToManyField(related_name='RTDefect_NDTMission', to='LAMProcessData.RTDefectInformation', verbose_name='X射线缺陷'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='RawStock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.RawStock', verbose_name='原材料批号'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='UT_defect',
            field=models.ManyToManyField(related_name='UTDefect_NDTMission', to='LAMProcessData.UTDefectInformation', verbose_name='超声缺陷'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='arrangement_date',
            field=models.DateField(blank=True, null=True, verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='available',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='任务完成时间'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='heat_treatment_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.HeatTreatmentState', verbose_name='热处理状态'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='machining_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.MachiningState', verbose_name='加工状态'),
        ),
        migrations.AlterField(
            model_name='nondestructivetest_mission',
            name='quality_reviewsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.QualityReviewSheet', verbose_name='不合格品审理单'),
        ),
    ]
