# Generated by Django 2.2 on 2020-05-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0073_auto_20200502_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lam_techinst_serial',
            old_name='selectable_PhyChemTest',
            new_name='selectable_PhyChemNonDestructiveTest',
        ),
        migrations.AlterField(
            model_name='rtdefectinformation',
            name='size',
            field=models.FloatField(verbose_name='缺陷大小(mm)'),
        ),
        migrations.AlterField(
            model_name='utdefectinformation',
            name='equivalent_hole_diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='当量平底孔直径(mm)'),
        ),
    ]
