# Generated by Django 2.2 on 2020-05-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0075_auto_20200502_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicochemicaltest_mission',
            name='LAM_product',
            field=models.ManyToManyField(blank=True, to='LAMProcessData.LAMProduct'),
        ),
        migrations.AlterField(
            model_name='rawstocksendretrieve',
            name='send_addition',
            field=models.ManyToManyField(blank=True, related_name='RawStockSendAddition_Send', to='LAMProcessData.RawStockSendAddition'),
        ),
    ]
