# Generated by Django 2.2 on 2020-05-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0076_auto_20200502_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtdefectinformation',
            old_name='DefectCode',
            new_name='defect_number',
        ),
        migrations.RenameField(
            model_name='ptdefectinformation',
            old_name='DefectCode',
            new_name='defect_number',
        ),
        migrations.RenameField(
            model_name='rtdefectinformation',
            old_name='DefectCode',
            new_name='defect_number',
        ),
        migrations.RenameField(
            model_name='utdefectinformation',
            old_name='DefectCode',
            new_name='defect_number',
        ),
    ]
