# Generated by Django 2.2 on 2020-05-14 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0078_remove_nondestructivetest_mission_ndt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamproductsubarea',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lamproductsubarea',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.LAMProductCategory', verbose_name='产品类别'),
        ),
        migrations.AlterField(
            model_name='lamproductsubarea',
            name='subarea_name',
            field=models.CharField(max_length=20, verbose_name='分区名称'),
        ),
    ]
