# Generated by Django 2.2 on 2020-06-17 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0079_auto_20200514_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingDingPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='./DingDingRecordPicture/', verbose_name='照片')),
            ],
        ),
        migrations.CreateModel(
            name='LAMProcess_PeriodEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.PositiveIntegerField()),
                ('finish_timestamp', models.PositiveIntegerField(blank=True)),
                ('summary', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LAMProcess_TransientEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_timestamp', models.PositiveIntegerField()),
                ('defect_type', models.CharField(choices=[('1', '修改全局变量'), ('2', '调整Z高度'), ('3', '调整零点坐标'), ('4', '更换粉嘴'), ('5', '清理粉嘴'), ('6', '吹除积粉'), ('7', '更换隔挡镜'), ('0', '其他')], max_length=2, verbose_name='操作类别')),
                ('summary', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OperatePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='./LAMOperationPicture/', verbose_name='照片')),
            ],
        ),
        migrations.AddField(
            model_name='lamprocess_worksection_operate',
            name='instant_timestamp',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defectpicture',
            name='picture',
            field=models.ImageField(upload_to='./DefectPicture/', verbose_name='缺陷照片'),
        ),
        migrations.AlterField(
            model_name='lamprocess_worksection_operate',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lamprocess_worksection_operate',
            name='operate_information',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lamproductsubarea',
            name='available',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='mtdefectinformation',
            name='defect_type',
            field=models.CharField(choices=[('Single', '单个缺陷'), ('Group', '成组缺陷')], max_length=10, verbose_name='磁粉缺陷类别'),
        ),
        migrations.CreateModel(
            name='LAMProcess_DingDingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_time', models.DateTimeField()),
                ('description', models.TextField(null=True, verbose_name='事件描述')),
                ('writer', models.CharField(max_length=16, null=True, verbose_name='日志填报人')),
                ('reporter', models.CharField(max_length=16, null=True, verbose_name='汇报人')),
                ('worksection_code', models.CharField(max_length=10, null=True, verbose_name='成形工段编号')),
                ('product_code', models.CharField(max_length=10, null=True, verbose_name='零件编号')),
                ('comment', models.TextField(null=True, verbose_name='评论信息')),
                ('photos', models.ManyToManyField(related_name='DingDingPicture_Record', to='LAMProcessData.DingDingPicture', verbose_name='照片')),
                ('product', models.ManyToManyField(blank=True, to='LAMProcessData.LAMProduct', verbose_name='零件实例')),
                ('work_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAMProcessData.Worksection', verbose_name='成形工段实例')),
            ],
        ),
        migrations.AddField(
            model_name='lamprocess_worksection_operate',
            name='photos',
            field=models.ManyToManyField(related_name='OperatePicture_LAMProcessOperation', to='LAMProcessData.OperatePicture'),
        ),
    ]
