# Generated by Django 2.2 on 2020-06-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0080_auto_20200617_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamprocess_dingdingrecord',
            name='acquisition_timestamp',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
