# Generated by Django 2.2 on 2020-02-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0021_auto_20200210_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process_Realtime_FineData_By_WorkSectionID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_timestamp', models.PositiveIntegerField(null=True)),
                ('oxygen_value', models.IntegerField(null=True)),
                ('laser_power', models.IntegerField(null=True)),
                ('X_value', models.FloatField(null=True)),
                ('Y_value', models.FloatField(null=True)),
                ('Z_value', models.FloatField(null=True)),
                ('ScanningRate_value', models.FloatField(null=True)),
                ('FeedRate_value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process_Realtime_FineData_By_WorkSectionID_1',
            fields=[
                ('process_realtime_finedata_by_worksectionid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LAMProcessData.Process_Realtime_FineData_By_WorkSectionID')),
            ],
            bases=('LAMProcessData.process_realtime_finedata_by_worksectionid',),
        ),
        migrations.CreateModel(
            name='Process_Realtime_FineData_By_WorkSectionID_2',
            fields=[
                ('process_realtime_finedata_by_worksectionid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LAMProcessData.Process_Realtime_FineData_By_WorkSectionID')),
            ],
            bases=('LAMProcessData.process_realtime_finedata_by_worksectionid',),
        ),
        migrations.CreateModel(
            name='Process_Realtime_FineData_By_WorkSectionID_3',
            fields=[
                ('process_realtime_finedata_by_worksectionid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LAMProcessData.Process_Realtime_FineData_By_WorkSectionID')),
            ],
            bases=('LAMProcessData.process_realtime_finedata_by_worksectionid',),
        ),
        migrations.CreateModel(
            name='Process_Realtime_FineData_By_WorkSectionID_4',
            fields=[
                ('process_realtime_finedata_by_worksectionid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LAMProcessData.Process_Realtime_FineData_By_WorkSectionID')),
            ],
            bases=('LAMProcessData.process_realtime_finedata_by_worksectionid',),
        ),
        migrations.CreateModel(
            name='Process_Realtime_FineData_By_WorkSectionID_5',
            fields=[
                ('process_realtime_finedata_by_worksectionid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LAMProcessData.Process_Realtime_FineData_By_WorkSectionID')),
            ],
            bases=('LAMProcessData.process_realtime_finedata_by_worksectionid',),
        ),
        migrations.CreateModel(
            name='Process_Realtime_FineData_By_WorkSectionID_6',
            fields=[
                ('process_realtime_finedata_by_worksectionid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LAMProcessData.Process_Realtime_FineData_By_WorkSectionID')),
            ],
            bases=('LAMProcessData.process_realtime_finedata_by_worksectionid',),
        ),
    ]
