# Generated by Django 2.2 on 2020-02-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0022_process_realtime_finedata_by_worksectionid_process_realtime_finedata_by_worksectionid_1_process_real'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_2',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_3',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_4',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_5',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_6',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_1',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_2',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_3',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_4',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_5',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_6',
        # ),
    ]
