# Generated by Django 2.2 on 2020-02-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0021_auto_20200210_0001'),
    ]
    #
    # dependencies = [
    #     ('LAMProcessData', '0023_auto_20200212_1604'),
    # ]

    operations = [
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_2',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_3',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_4',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_5',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_6',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='process_realtime_finedata_by_worksectionid_ptr',
        # ),
        # migrations.AddField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='FeedRate_value',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='ScanningRate_value',
        #     field=models.FloatField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='X_value',
        #     field=models.FloatField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='Y_value',
        #     field=models.FloatField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='Z_value',
        #     field=models.FloatField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='acquisition_timestamp',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='laser_power',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='process_realtime_finedata_by_worksectionid_1',
        #     name='oxygen_value',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_2',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_3',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_4',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_5',
        # ),
        # migrations.DeleteModel(
        #     name='Process_Realtime_FineData_By_WorkSectionID_6',
        # ),
    ]
