# Generated by Django 2.2 on 2020-02-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMProcessData', '0023_auto_20200212_1604'),
        ('LAMProcessData', '0024_auto_20200212_1612'),
    ]

    operations = [
    ]
